/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ClientSupportRouteImport } from './routes/client/support'
import { Route as ClientSettingsRouteImport } from './routes/client/settings'
import { Route as ClientSamplesRouteImport } from './routes/client/samples'
import { Route as ClientProjectsRouteImport } from './routes/client/projects'
import { Route as ClientProductionRouteImport } from './routes/client/production'
import { Route as ClientOrdersRouteImport } from './routes/client/orders'
import { Route as ClientNewRequestRouteImport } from './routes/client/new-request'
import { Route as ClientMessagingRouteImport } from './routes/client/messaging'
import { Route as ClientDocumentsRouteImport } from './routes/client/documents'
import { Route as ClientDesignApprovalsRouteImport } from './routes/client/design-approvals'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminBuilderRouteImport } from './routes/admin/builder'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientSupportRoute = ClientSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSamplesRoute = ClientSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProductionRoute = ClientProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ClientRoute,
} as any)
const ClientOrdersRoute = ClientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNewRequestRoute = ClientNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMessagingRoute = ClientMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDesignApprovalsRoute = ClientDesignApprovalsRouteImport.update({
  id: '/design-approvals',
  path: '/design-approvals',
  getParentRoute: () => ClientRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/cosmetics': typeof CosmeticsRoute
  '/industries': typeof IndustriesRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/content': typeof AdminContentRoute
  '/client/design-approvals': typeof ClientDesignApprovalsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/messaging': typeof ClientMessagingRoute
  '/client/new-request': typeof ClientNewRequestRoute
  '/client/orders': typeof ClientOrdersRoute
  '/client/production': typeof ClientProductionRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/samples': typeof ClientSamplesRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builder': typeof BuilderRoute
  '/contact': typeof ContactRoute
  '/cosmetics': typeof CosmeticsRoute
  '/industries': typeof IndustriesRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/content': typeof AdminContentRoute
  '/client/design-approvals': typeof ClientDesignApprovalsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/messaging': typeof ClientMessagingRoute
  '/client/new-request': typeof ClientNewRequestRoute
  '/client/orders': typeof ClientOrdersRoute
  '/client/production': typeof ClientProductionRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/samples': typeof ClientSamplesRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/builder': typeof BuilderRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/cosmetics': typeof CosmeticsRoute
  '/industries': typeof IndustriesRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/content': typeof AdminContentRoute
  '/client/design-approvals': typeof ClientDesignApprovalsRoute
  '/client/documents': typeof ClientDocumentsRoute
  '/client/messaging': typeof ClientMessagingRoute
  '/client/new-request': typeof ClientNewRequestRoute
  '/client/orders': typeof ClientOrdersRoute
  '/client/production': typeof ClientProductionRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/samples': typeof ClientSamplesRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/builder'
    | '/client'
    | '/contact'
    | '/cosmetics'
    | '/industries'
    | '/process'
    | '/services'
    | '/admin/builder'
    | '/admin/content'
    | '/client/design-approvals'
    | '/client/documents'
    | '/client/messaging'
    | '/client/new-request'
    | '/client/orders'
    | '/client/production'
    | '/client/projects'
    | '/client/samples'
    | '/client/settings'
    | '/client/support'
    | '/admin/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/builder'
    | '/contact'
    | '/cosmetics'
    | '/industries'
    | '/process'
    | '/services'
    | '/admin/builder'
    | '/admin/content'
    | '/client/design-approvals'
    | '/client/documents'
    | '/client/messaging'
    | '/client/new-request'
    | '/client/orders'
    | '/client/production'
    | '/client/projects'
    | '/client/samples'
    | '/client/settings'
    | '/client/support'
    | '/admin'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/builder'
    | '/client'
    | '/contact'
    | '/cosmetics'
    | '/industries'
    | '/process'
    | '/services'
    | '/admin/builder'
    | '/admin/content'
    | '/client/design-approvals'
    | '/client/documents'
    | '/client/messaging'
    | '/client/new-request'
    | '/client/orders'
    | '/client/production'
    | '/client/projects'
    | '/client/samples'
    | '/client/settings'
    | '/client/support'
    | '/admin/'
    | '/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  CosmeticsRoute: typeof CosmeticsRoute
  IndustriesRoute: typeof IndustriesRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/support': {
      id: '/client/support'
      path: '/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof ClientSupportRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/samples': {
      id: '/client/samples'
      path: '/samples'
      fullPath: '/client/samples'
      preLoaderRoute: typeof ClientSamplesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/production': {
      id: '/client/production'
      path: '/production'
      fullPath: '/client/production'
      preLoaderRoute: typeof ClientProductionRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/orders': {
      id: '/client/orders'
      path: '/orders'
      fullPath: '/client/orders'
      preLoaderRoute: typeof ClientOrdersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/new-request': {
      id: '/client/new-request'
      path: '/new-request'
      fullPath: '/client/new-request'
      preLoaderRoute: typeof ClientNewRequestRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/messaging': {
      id: '/client/messaging'
      path: '/messaging'
      fullPath: '/client/messaging'
      preLoaderRoute: typeof ClientMessagingRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/design-approvals': {
      id: '/client/design-approvals'
      path: '/design-approvals'
      fullPath: '/client/design-approvals'
      preLoaderRoute: typeof ClientDesignApprovalsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuilderRoute: typeof AdminBuilderRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuilderRoute: AdminBuilderRoute,
  AdminContentRoute: AdminContentRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientDesignApprovalsRoute: typeof ClientDesignApprovalsRoute
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientMessagingRoute: typeof ClientMessagingRoute
  ClientNewRequestRoute: typeof ClientNewRequestRoute
  ClientOrdersRoute: typeof ClientOrdersRoute
  ClientProductionRoute: typeof ClientProductionRoute
  ClientProjectsRoute: typeof ClientProjectsRoute
  ClientSamplesRoute: typeof ClientSamplesRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientSupportRoute: typeof ClientSupportRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDesignApprovalsRoute: ClientDesignApprovalsRoute,
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientMessagingRoute: ClientMessagingRoute,
  ClientNewRequestRoute: ClientNewRequestRoute,
  ClientOrdersRoute: ClientOrdersRoute,
  ClientProductionRoute: ClientProductionRoute,
  ClientProjectsRoute: ClientProjectsRoute,
  ClientSamplesRoute: ClientSamplesRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientSupportRoute: ClientSupportRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BuilderRoute: BuilderRoute,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  CosmeticsRoute: CosmeticsRoute,
  IndustriesRoute: IndustriesRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
